### ISSUE TITLE
Feature: User can add a recipe

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a recipe name with an image, a list of ingredients, instructions to make it, and other notes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user is presented with a text entry form that allows them to enter a dish name, list of ingredients, instructions on how to make it, and optional notes at the end.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![add recipe mobile](https://user-images.githubusercontent.com/64382900/157802846-6bb370e4-e7d5-46e1-9ad7-064d40a5a8b9.JPG)
![add recipe desktop](https://user-images.githubusercontent.com/64382900/157802869-bbba5a49-8ab5-4f40-a212-98e7bfa57d52.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `recipes.sql` to automatically increment a recipeId, add name, instructions, notes, date saved
- [x] Update `ingredients.sql` to register new ingredients automatically increment an ingredientId
- [x] Update `recipeIngredients.sql` to connect recipeId to ingredientId and add ingredient quantity

### ☁️ Server

- [x] Create `server/index.js` to handle changes to the form's text field
- [x] Update `server/index.js` to handle submitting to database and resetting of the form
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the add entry form with required and optional text fields
  - [x] Contain the entire form as a sort of card
  - [x] Include submit and cancel buttons
- [x] Create a component to act as the top header
- [x] Create a component to act as the bottom navbar

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by J0N-C** [comment]
Moved Ingredients List and Images to separate feature
Navbar not implemented yet
Cancel not implemented yet
