### ISSUE TITLE
Bug: Adding the same tag causes an error because tag names are supposed to be unique

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/final-project#11]
#### Desired Behavior

> ##### The app should ...

Adding a recipe with a tag that already exists should create a new recipeId and TagId association in recipeTags

#### Actual Behavior

> ##### The app does this instead ...

Tries to add another tag with the same name and causes an error

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Add a new recipe and give it a tag that has already been used in another recipe

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] When posting a tag, figure out if the tag exists. If it does, add its tagId to recipeTags with the new recipe's ID. If it does not, create the tag.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
