### ISSUE TITLE
Feature: User can view their saved recipes

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of the recipes they've saved as compact cards, then click one to see a full enlarged version.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user is shown a list of all recipes they have saved as compact cards that only display the dish name, image, tags, date created, and date that they last made this dish, if ever. 
If they click a card, they are shown a full size card including ingredients, instructions, and notes.
The user can click a button to update the last made date to the current day, or a button to go back to the list of compact recipes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![view recipe mobile](https://user-images.githubusercontent.com/64382900/157804665-5533774d-967c-4c54-b4e5-eb6e639f0390.JPG)
![view recipe desktop](https://user-images.githubusercontent.com/64382900/157804672-5627c831-605f-4373-bc83-de4a144400c0.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `recipe.sql` to reflect the new day which a recipe was last made

### ☁️ Server

- [x] Update `server/index.js` to send a GET request to the database for all recipes that the user has saved
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the condensed recipe information as compact cards
- [x] Add navbar for switching views
- [x] Clicking cancel on add-recipe returns user to view-recipe
  - [x] Each component has a listener for when it is clicked, to expand to a full size card 
- [x] Create a component to display the full recipe card when a compact card is clicked, and can go back to the list of compact cards
- [x] Update the navbar component to reflect that the user is currently viewing recipes and allow the user to go back to adding recipes with the new recipes button.

### 🧑‍⚕️ Clean Up

- [x] Ignore edit and delete functionality buttons of wireframe in this issue, add in subsequent
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
