### ISSUE TITLE
Feature: User can edit a recipe

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Edit a recipe they previously added
Also, refactor add-recipe so that user can add multiple lines of ingredients, split into amount, ingredient name, and preparation method. These are then saved in the table under ingredients, recipeIngredients.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click onto a specific recipe. There is an edit icon (pencil) that when clicked, populates an edit form, where the user can see their previously entered information and make changes. They can then cancel or save these changes. The page automatically goes to viewing that edited recipe.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![edit recipe mobile](https://user-images.githubusercontent.com/64382900/160733776-08b39b6b-673d-4cc6-bc1d-fb1ad52172b3.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update table when changes are submitted
- [x] Add ability to insert into and change ingredients and recipeIngredients table

### ☁️ Server

- [x] Update  `server/index.js` to handle multiple ingredient row insert.
- [x] Update `server/index.js` to accept PUT requests to update the table, changing values that the user has changed
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to allow edits. 
- [x] Create a component to allow multiple ingredient information entering.
- [x] Alternative: Edit the new-recipe form to allow edits?

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by J0N-C** [comment]
Edited format of add-ingredients box, need to update figma
Consider updating instructions box to be similar
