### ISSUE TITLE
Feature: User can delete a recipe

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Delete a recipe they don't want or need anymore

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

At the bottom of a full recipe card there is a trash can icon that when clicked, opens a confirmation to delete. If cancel is clicked, the popup is closed. If confirmed, the recipe is deleted and the user is taken back to viewing their list of compact recipes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![delete-recipe-before-click](https://user-images.githubusercontent.com/64382900/162355352-490432e4-ec58-4ccd-b72f-3e444a486d2c.JPG)
![delete-recipe-confirm](https://user-images.githubusercontent.com/64382900/162355356-d29818e5-ba32-4762-97ae-e9f12fe4ed2c.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to have a default test recipe for delete purposes

### ☁️ Server

- [x] Update `server/index.js` to handle delete requests and send the right delete query to the server
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the view full card component to have a delete recipe confirmation popup, opened by a delete trashcan icon on the full card.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
