### ISSUE TITLE
Feature: User can search their saved recipes

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search keywords within title, ingredients, or tags for certain recipes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There will be a search page, which has inputs to search by certain methods (recipe name, recipe ingredient, or recipe tags). When a valid search is made, the results of matching recipes are displayed. If there are no results, it tells the user this and re-displays the search inputs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![search recipe figma](https://user-images.githubusercontent.com/64382900/162863072-761aa782-23e9-4b3f-ac46-f8eea2905849.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component for the search page with inputs for searches
- [x] Create a component for the search page to display results

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
