### ISSUE TITLE
Feature: User can log in to add, save, and view recipes

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register with their email or log in to be able to save and view their recipes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On opening the web page there is a prompt to log in, if the user is not currently logged in. If they do not have an account, they can register. They can also then log out at the end of their session for security.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to require authentication for all recipe-related processes to ensure the proper user is accessing their recipes.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to act as the login/registration page
- [x] Update homepage to redirect to login at start, or view recipes if logged in.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
